# Generated by Django 6.0.6 on 2026-06-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('average_check', models.DecimalField(decimal_places=2, max_digits=8)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
